FROM apache/spark:3.5.1

USER root

RUN pip install --no-cache-dir \
    pyspark==3.5.1 \
    pandas \
    reverse_geocoder

# ------------------------------------------------------------
# Cài thêm các thư viện Hadoop + AWS SDK + PostgreSQL JDBC
# ------------------------------------------------------------
RUN curl -L https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
        -o /opt/spark/jars/hadoop-aws-3.3.4.jar && \
    curl -L https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar \
        -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar && \
    curl -L https://jdbc.postgresql.org/download/postgresql-42.7.1.jar \
        -o /opt/spark/jars/postgresql-42.7.1.jar && \
    chmod 644 /opt/spark/jars/*.jar

# ------------------------------------------------------------
# Copy code Spark
# ------------------------------------------------------------
RUN mkdir -p /opt/spark/app
COPY ./spark/jobs/cleaning.py /opt/spark/app/cleaning.py

# ------------------------------------------------------------
# Copy cấu hình Spark (khuyến nghị)
# Cho phép override bằng ConfigMap nếu chạy K8s
# ------------------------------------------------------------
COPY conf/core-site.xml /opt/spark/conf/core-site.xml
COPY conf/spark-defaults.conf /opt/spark/conf/spark-defaults.conf

USER 185

